package com.vanguard.apx.webservice.domain.api;

import java.util.ArrayList;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "AccountProfile")
public class Account {
	private long AccountId;
	public Account() {
		super();
	}
	private String accountName;
	private String profileId;
	private int totalBalance;
	List<Holding> holding = new ArrayList<>();
	 @DynamoDBHashKey
	 @DynamoDBAutoGeneratedKey
	public long getAccountId() {
		return AccountId;
	}
	public void setAccountId(long accountId) {
		AccountId = accountId;
	}
	 @DynamoDBAttribute
	public String getAccountName() {
		return accountName;
	}
	public void setAccountName(String accountName) {
		this.accountName = accountName;
	}
	 @DynamoDBAttribute
	public String getProfileId() {
		return profileId;
	}
	public void setProfileId(String profileId) {
		this.profileId = profileId;
	}
	 @DynamoDBAttribute
	public int getTotalBalance() {
		return totalBalance;
	}
	public void setTotalBalance(int totalBalance) {
		this.totalBalance = totalBalance;
	}
	 @DynamoDBAttribute
	public List<Holding> getHolding() {
		return holding;
	}
	public void setHolding(List<Holding> holding) {
		this.holding = holding;
	}
	public Account(long accountId, String accountName, String profileId, int totalBalance, List<Holding> holding) {
		super();
		AccountId = accountId;
		this.accountName = accountName;
		this.profileId = profileId;
		this.totalBalance = totalBalance;
		this.holding = holding;
	}
	

}
